export type Status = 'meets' | 'partial' | 'gap';
export type Authority = 'FDA' | 'EMA' | 'AVMA';

export interface ComplianceItem {
  authority: Authority;
  requirement: string;
  requirement_en: string;
  reference: string;
  evidence: string;
  evidence_en: string;
  artifact: string;
  status: Status;
  action: string;
  action_en: string;
  effort?: 'S' | 'M' | 'L';
  priority?: 'P0' | 'P1' | 'P2' | 'P3';
}

export const COMPLIANCE_ITEMS: ComplianceItem[] = [
  // ===== FDA =====
  {
    authority: 'FDA',
    requirement: 'Predetermined Change Control Plan (PCCP)',
    requirement_en: 'Predetermined Change Control Plan (PCCP)',
    reference: 'FDA Draft Guidance Jan/2025',
    evidence: 'Versionamento via CHANGELOG.md + I18N_VERSION + migrations Supabase com auditoria',
    evidence_en: 'Versioning via CHANGELOG.md + I18N_VERSION + Supabase migrations with audit trail',
    artifact: 'CHANGELOG.md, supabase/migrations/, src/i18n.ts',
    status: 'meets',
    action: 'Formalizar PCCP em documento assinado',
    action_en: 'Formalize PCCP in a signed document',
    priority: 'P2', effort: 'S',
  },
  {
    authority: 'FDA',
    requirement: 'Good Machine Learning Practice (GMLP) — 10 princípios',
    requirement_en: 'Good Machine Learning Practice (GMLP) — 10 principles',
    reference: 'FDA/Health Canada/MHRA GMLP',
    evidence: 'Edge functions com logging, separação treino/inferência, prompts versionados',
    evidence_en: 'Edge functions with logging, train/inference separation, versioned prompts',
    artifact: 'supabase/functions/*, PromptConfigurationTab',
    status: 'partial',
    action: 'Documentar matriz GMLP × função explicitamente',
    action_en: 'Explicitly document GMLP × function matrix',
    priority: 'P1', effort: 'M',
  },
  {
    authority: 'FDA',
    requirement: 'Transparência para usuários',
    requirement_en: 'Transparency for users',
    reference: 'FDA AI/ML Transparency Principles',
    evidence: 'ClinicalPipelineLogPanel, DigitalTwinLogPanel, EvidenceGapLogPanel, DrugLookupBadge',
    evidence_en: 'ClinicalPipelineLogPanel, DigitalTwinLogPanel, EvidenceGapLogPanel, DrugLookupBadge',
    artifact: 'src/components/pet/*LogPanel.tsx',
    status: 'meets',
    action: 'Adicionar model card por feature',
    action_en: 'Add per-feature model card',
    priority: 'P2', effort: 'M',
  },
  {
    authority: 'FDA',
    requirement: 'Monitoramento de performance no mundo real',
    requirement_en: 'Real-World Performance Monitoring',
    reference: 'FDA Draft Guidance §VII',
    evidence: 'Sem cohort tracking longitudinal pós-deploy',
    evidence_en: 'No post-deploy longitudinal cohort tracking',
    artifact: '— (gap)',
    status: 'gap',
    action: 'Implementar tabela outcome_observations + dashboard',
    action_en: 'Implement outcome_observations table + dashboard',
    priority: 'P0', effort: 'L',
  },
  {
    authority: 'FDA',
    requirement: 'Mitigação de viés e performance por subgrupo',
    requirement_en: 'Bias mitigation & subgroup performance',
    reference: 'GMLP Princípio 3',
    evidence: 'Política bilíngue PT/EN, dictionaries SNOMED/UMLS, foco canino documentado',
    evidence_en: 'Bilingual PT/EN policy, SNOMED/UMLS dictionaries, documented canine focus',
    artifact: 'src/data/biomedical-taxonomy.ts',
    status: 'partial',
    action: 'Avaliar viés por raça/porte e publicar relatório',
    action_en: 'Evaluate breed/size bias and publish a report',
    priority: 'P1', effort: 'M',
  },
  {
    authority: 'FDA',
    requirement: 'Qualidade e integridade dos dados',
    requirement_en: 'Data quality & integrity',
    reference: 'GMLP Princípio 4',
    evidence: 'No-mock policy, curation gatekeeper, two-tier governance, SHA-256 dedup',
    evidence_en: 'No-mock policy, curation gatekeeper, two-tier governance, SHA-256 dedup',
    artifact: 'mem://principles/curation-gatekeeper-for-vetgraphrag',
    status: 'meets',
    action: 'Auditoria periódica de integridade automatizada',
    action_en: 'Automated periodic integrity audit',
    priority: 'P2', effort: 'S',
  },

  // ===== EMA =====
  {
    authority: 'EMA',
    requirement: 'Classificação como sistema de IA de alto risco',
    requirement_en: 'Classification as high-risk AI system',
    reference: 'EU AI Act Anexo III + EMA Reflection Paper Sep/2024',
    evidence: 'Sistema de apoio à decisão clínica veterinária — fora do escopo médico humano do EU AI Act, mas adota controles equivalentes',
    evidence_en: 'Veterinary clinical decision support — outside EU AI Act human-medical scope but adopts equivalent controls',
    artifact: 'docs/TECHNICAL_DECISIONS.md',
    status: 'partial',
    action: 'Publicar declaração formal de classificação',
    action_en: 'Publish formal classification statement',
    priority: 'P1', effort: 'S',
  },
  {
    authority: 'EMA',
    requirement: 'Supervisão humana (Art. 14)',
    requirement_en: 'Human oversight (Art. 14)',
    reference: 'EU AI Act Art. 14',
    evidence: 'VetRecommendationPanel: aceitar/modificar/rejeitar; curadoria humana antes do KG',
    evidence_en: 'VetRecommendationPanel: accept/modify/reject; human curation before KG',
    artifact: 'src/components/pet/VetRecommendationPanel.tsx',
    status: 'meets',
    action: 'Logar override do veterinário com justificativa',
    action_en: 'Log veterinarian overrides with justification',
    priority: 'P2', effort: 'S',
  },
  {
    authority: 'EMA',
    requirement: 'Documentação técnica (Anexo IV)',
    requirement_en: 'Technical documentation (Annex IV)',
    reference: 'EU AI Act Annex IV',
    evidence: 'ARCHITECTURE.md, CURRENT_STATE.md, STANFORD_DEMO.md, CHANGELOG.md',
    evidence_en: 'ARCHITECTURE.md, CURRENT_STATE.md, STANFORD_DEMO.md, CHANGELOG.md',
    artifact: 'docs/, ARCHITECTURE.md',
    status: 'meets',
    action: 'Consolidar em dossiê único exportável',
    action_en: 'Consolidate into a single exportable dossier',
    priority: 'P2', effort: 'M',
  },
  {
    authority: 'EMA',
    requirement: 'Logging e rastreabilidade',
    requirement_en: 'Logging & traceability',
    reference: 'EU AI Act Art. 12',
    evidence: 'study_audit_logs, KG provenance, triplet_extractions com source_id',
    evidence_en: 'study_audit_logs, KG provenance, triplet_extractions with source_id',
    artifact: 'tables study_audit_logs, hierarchical_edges',
    status: 'meets',
    action: 'Formalizar retenção mínima de 6 meses',
    action_en: 'Formalize 6-month minimum retention',
    priority: 'P3', effort: 'S',
  },
  {
    authority: 'EMA',
    requirement: 'Acurácia, robustez e cibersegurança',
    requirement_en: 'Accuracy, robustness, cybersecurity',
    reference: 'EU AI Act Art. 15',
    evidence: 'RLS em todas tabelas, secrets isolados, validation triggers, has_role()',
    evidence_en: 'RLS on all tables, isolated secrets, validation triggers, has_role()',
    artifact: 'supabase/migrations/, RLS policies',
    status: 'meets',
    action: 'Pen-test anual + SAST/DAST contínuo',
    action_en: 'Annual pen-test + continuous SAST/DAST',
    priority: 'P1', effort: 'M',
  },
  {
    authority: 'EMA',
    requirement: 'Governança de dados (Art. 10)',
    requirement_en: 'Data governance (Art. 10)',
    reference: 'EU AI Act Art. 10',
    evidence: 'Base knowledge governance manual, soft-delete, two-tier confidence (>=50% auto)',
    evidence_en: 'Manual base knowledge governance, soft-delete, two-tier confidence (>=50% auto)',
    artifact: 'mem://architecture/clinical-data-quality-two-tier-governance',
    status: 'partial',
    action: 'Documentar política de dataset (origem, consentimento)',
    action_en: 'Document dataset policy (provenance, consent)',
    priority: 'P1', effort: 'M',
  },

  // ===== AVMA =====
  {
    authority: 'AVMA',
    requirement: 'Veterinário no loop',
    requirement_en: 'Veterinarian-in-the-loop',
    reference: 'AVMA Framework Nov/2025',
    evidence: 'Pipeline de curadoria de 7 estágios; nada chega ao KG sem aprovação humana (excl. >=50% auto)',
    evidence_en: '7-stage curation pipeline; nothing reaches KG without human approval (except >=50% auto)',
    artifact: 'TripletCurationBoard, hybrid-recommendation',
    status: 'meets',
    action: 'Tornar threshold auto-approve configurável por admin',
    action_en: 'Make auto-approve threshold admin-configurable',
    priority: 'P2', effort: 'S',
  },
  {
    authority: 'AVMA',
    requirement: 'Validação por espécie',
    requirement_en: 'Species-specific validation',
    reference: 'AVMA Framework §3.2',
    evidence: 'Foco exclusivo canino documentado; sem validação cruzada felina/equina',
    evidence_en: 'Canine-only focus documented; no feline/equine cross-validation',
    artifact: 'mem://clinical/vetgraphrag-diagnostic-scope-constraints',
    status: 'gap',
    action: 'Marcar species=canine em todo triplet + bloquear extrapolação',
    action_en: 'Tag species=canine on every triplet + block extrapolation',
    priority: 'P0', effort: 'M',
  },
  {
    authority: 'AVMA',
    requirement: 'Divulgação de uso off-label',
    requirement_en: 'Off-label disclosure',
    reference: 'AVMA Framework §4.1',
    evidence: 'DrugLookupBadge sinaliza uso humano/extra-label e disclaimer',
    evidence_en: 'DrugLookupBadge flags human/extra-label use and disclaimer',
    artifact: 'src/components/pet/DrugLookupBadge.tsx',
    status: 'meets',
    action: 'Adicionar tela de consentimento para o tutor',
    action_en: 'Add consent screen for the owner',
    priority: 'P2', effort: 'S',
  },
  {
    authority: 'AVMA',
    requirement: 'Educação continuada para usuários',
    requirement_en: 'Continuing education for users',
    reference: 'AVMA Framework §6',
    evidence: 'Sem módulo de CE/treinamento integrado',
    evidence_en: 'No integrated CE/training module',
    artifact: '— (gap)',
    status: 'gap',
    action: 'Criar onboarding + biblioteca de evidência por composto',
    action_en: 'Create onboarding + evidence library per compound',
    priority: 'P1', effort: 'L',
  },
  {
    authority: 'AVMA',
    requirement: 'Transparência sobre limitações',
    requirement_en: 'Transparency on limitations',
    reference: 'AVMA Framework §5',
    evidence: 'Insight cards e badges indicam confiança; gap de evidência via EvidenceGapLogPanel',
    evidence_en: 'Insight cards and badges show confidence; evidence gap via EvidenceGapLogPanel',
    artifact: 'EvidenceGapLogPanel, recommendation-confidence-service',
    status: 'meets',
    action: 'Disclaimer permanente no rodapé das recomendações',
    action_en: 'Permanent disclaimer at recommendation footer',
    priority: 'P3', effort: 'S',
  },
];