INSERT INTO public.permissions (key, category, label_pt, label_en, description_pt, description_en, supports_edit) VALUES
  ('admin.access','app','Acessar o painel administrativo','Access the admin panel',NULL,NULL,true),
  ('op.curate_approve','operation','Aprovar curadoria','Approve curation',NULL,NULL,true),
  ('op.enrich_knowledge_graph','operation','Enriquecer o grafo de conhecimento','Enrich the knowledge graph',NULL,NULL,true),
  ('op.extract_study_entities','operation','Extrair entidades do estudo','Extract study entities',NULL,NULL,true),
  ('op.force_reextract','operation','Forçar reextração','Force re-extraction',NULL,NULL,true),
  ('op.gemini_file_search','operation','Analisar estudo com IA','Analyze study with AI',NULL,NULL,true),
  ('op.generate_triplets','operation','Gerar triplets','Generate triplets',NULL,NULL,true),
  ('op.manage_permissions','operation','Editar permissões','Edit permissions',NULL,NULL,true),
  ('op.manage_users','operation','Gerenciar usuários e papéis','Manage users and roles',NULL,NULL,true),
  ('op.parse_study','operation','Processar PDF de estudo','Parse study PDF',NULL,NULL,true),
  ('tab.about-senex','tab:configuration','About Senex AI','About Senex AI',NULL,NULL,true),
  ('tab.access-requests','tab:configuration','Usuários & Perfis','Users & Roles',NULL,NULL,true),
  ('tab.actions','tab:configuration','Ações','Bulk Actions',NULL,NULL,true),
  ('tab.ai-insights','tab:knowledge-base','A.I. Insights','A.I. Insights',NULL,NULL,true),
  ('tab.analytics','tab:configuration','Analytics','Analytics',NULL,NULL,true),
  ('tab.breeds-management','tab:knowledge-base','Raças & Predisposições','Breeds & Predispositions',NULL,NULL,true),
  ('tab.clinical-monitoring','tab:data-processing','Monitoramento Clínico','Clinical Monitoring',NULL,NULL,true),
  ('tab.compliance-dashboard','tab:configuration','Conformidade Regulatória','Regulatory Compliance',NULL,NULL,true),
  ('tab.config-ia','tab:configuration','Configurações IA','AI Settings',NULL,NULL,true),
  ('tab.custo-beneficio','tab:predictive-analysis','Análise de ROI','ROI Analysis',NULL,NULL,true),
  ('tab.design-conventions','tab:configuration','Design','Design',NULL,NULL,true),
  ('tab.dosage-curation','tab:knowledge-base','Curadoria de Doses','Dosage Curation',NULL,NULL,true),
  ('tab.estudos','tab:knowledge-base','Estudos Científicos','Scientific Studies',NULL,NULL,true),
  ('tab.estudos-andamento','tab:research','Em Andamento','Ongoing Studies',NULL,NULL,true),
  ('tab.estudos-concluidos','tab:research','Concluídos','Completed Studies',NULL,NULL,true),
  ('tab.estudos-planejados','tab:research','Planejados','Planned Studies',NULL,NULL,true),
  ('tab.evidence-conflicts','tab:knowledge-base','Conflitos de Evidência','Evidence Conflicts',NULL,NULL,true),
  ('tab.external-sources','tab:knowledge-base','Fontes Externas','External Sources',NULL,NULL,true),
  ('tab.fundamentos','tab:configuration','Fundamentos Arquiteturais','Architectural Foundations',NULL,NULL,true),
  ('tab.gapfill-diagnostics','tab:knowledge-base','Diagnóstico Gap-Fill','Gap-Fill Diagnostics',NULL,NULL,true),
  ('tab.import','tab:data-processing','Importação','Import',NULL,NULL,true),
  ('tab.knowledge-graph','tab:knowledge-base','Knowledge Graph','Knowledge Graph',NULL,NULL,true),
  ('tab.lab-references','tab:knowledge-base','Referências Laboratoriais','Lab References',NULL,NULL,true),
  ('tab.modelos','tab:predictive-analysis','Modelos Preditivos','Predictive Models',NULL,NULL,true),
  ('tab.nutraceuticals-unified','tab:knowledge-base','Nutracêuticos','Nutraceuticals',NULL,NULL,true),
  ('tab.ontology-audit','tab:knowledge-base','Ontologia (legado)','Ontology (legacy)',NULL,NULL,true),
  ('tab.organograma','tab:configuration','Organograma do Projeto','Project Org Chart',NULL,NULL,true),
  ('tab.pesquisa-estudos','tab:research','Pesquisa','Study Search',NULL,NULL,true),
  ('tab.pet-food-catalog','tab:knowledge-base','Catálogo de Rações','Pet Food Catalog',NULL,NULL,true),
  ('tab.pet-food-coverage','tab:knowledge-base','Cobertura de Rações','Pet Food Coverage',NULL,NULL,true),
  ('tab.pet-management','tab:data-processing','Análise de Pacientes','Patient Analysis',NULL,NULL,true),
  ('tab.pharmacology','tab:knowledge-base','Base Farmacológica','Pharmacology Base',NULL,NULL,true),
  ('tab.predictive-analysis-settings','tab:predictive-analysis','Configurações','Predictive Analysis Settings',NULL,NULL,true),
  ('tab.priorizacoes','tab:research','AI Scientist','AI Scientist',NULL,NULL,true),
  ('tab.prompts','tab:configuration','AI Prompts','AI Prompts',NULL,NULL,true),
  ('tab.relacoes','tab:knowledge-base','Relações','Relations',NULL,NULL,true),
  ('tab.research-settings','tab:research','Configurações','Research Settings',NULL,NULL,true),
  ('tab.sugestoes-ai','tab:research','Sugestões AI','AI Suggestions',NULL,NULL,true),
  ('tab.technical-audits','tab:configuration','Auditorias Técnicas','Technical Audits',NULL,NULL,true),
  ('tab.translation-audit','tab:configuration','Traduções (auditoria)','Translations (audit)',NULL,NULL,true),
  ('tab.translation-manager','tab:configuration','Traduções (gestão)','Translations (manage)',NULL,NULL,true),
  ('tab.translations','tab:configuration','Traduções','Translations',NULL,NULL,true),
  ('tab.triplet-curation','tab:knowledge-base','Triplets','Triplets',NULL,NULL,true),
  ('tab.tutorial-ia','tab:configuration','Tutorial — Governança IA','Tutorial — AI Governance',NULL,NULL,true),
  ('tab.verification-runs','tab:knowledge-base','Verificação Independente','Independent Verification',NULL,NULL,true),
  ('tab.veterinary-targets','tab:knowledge-base','Alvos Veterinários','Veterinary Targets',NULL,NULL,true),
  ('tab.visualization','tab:data-processing','Visualização','Visualization',NULL,NULL,true)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.role_permissions (role, permission_key, level)
SELECT 'admin', p.key, 'edit' FROM public.permissions p
ON CONFLICT (role, permission_key) DO NOTHING;