
INSERT INTO public.compound_dosage_reference
  (compound_name_en, condition_name_en, species, min_mg_per_kg, max_mg_per_kg, unit, frequency_per_day, route, source_type, source_url, source_citation, confidence, needs_review, notes)
VALUES
  ('Astaxanthin', 'Osteoarthritis', 'canine', 0.5, 2.0, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/20374748/', 'Park JS et al., 2010 — Astaxanthin in companion animals', 0.85, false, 'Anti-inflamatório carotenoide, biodisponibilidade aumentada com gordura.'),
  ('Astaxanthin', NULL, 'canine', 0.5, 2.0, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/20374748/', 'Park JS et al., 2010', 0.8, false, 'Dose geral antioxidante.'),
  ('Quercetin', 'Inflammation', 'canine', 5, 25, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/26134033/', 'Boots AW et al., 2008 — Quercetin pharmacokinetics', 0.75, false, 'Flavonoide, sinergia com bromelina/vitamina C.'),
  ('Quercetin', 'Osteoarthritis', 'canine', 5, 25, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/26134033/', 'Boots AW et al., 2008', 0.7, false, 'Modula NF-kB, considerar com gordura para absorção.'),
  ('Curcumin', 'Inflammation', 'canine', 50, 200, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/12676044/', 'Innes JF et al., 2003 — Curcuma in canine OA', 0.8, false, 'Use formulação com piperina ou liposomal para absorção.'),
  ('Curcumin', 'Osteoarthritis', 'canine', 50, 200, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/12676044/', 'Innes JF et al., 2003', 0.85, false, 'COX-2 inhibition. Dose dividida.'),
  ('Omega-3 Fatty Acids', 'Osteoarthritis', 'canine', 50, 100, 'mg/kg', 1, 'oral', 'curated_study', 'https://avmajournals.avma.org/view/journals/javma/236/1/javma.236.1.59.xml', 'Roush JK et al., 2010 — JAVMA EPA+DHA in OA', 0.92, false, 'EPA+DHA combinados; dose pelo EPA+DHA, não pelo óleo total.'),
  ('Omega-3 Fatty Acids', 'Cardiac Disease', 'canine', 60, 120, 'mg/kg', 1, 'oral', 'curated_study', 'https://onlinelibrary.wiley.com/doi/10.1111/j.1939-1676.2007.tb02923.x', 'Smith CE et al., 2007 — ACVIM EPA+DHA in cardiac', 0.88, false, 'Cardiomiopatia / DMVD.'),
  ('Omega-3 Fatty Acids', 'Inflammation', 'canine', 50, 100, 'mg/kg', 1, 'oral', 'curated_study', 'https://avmajournals.avma.org/view/journals/javma/236/1/javma.236.1.59.xml', 'Roush JK 2010 / WSAVA Guidelines', 0.9, false, 'Anti-inflamatório sistêmico.'),
  ('Omega-3 Fatty Acids', NULL, 'canine', 30, 70, 'mg/kg', 1, 'oral', 'curated_study', 'https://wsava.org/global-guidelines/global-nutrition-guidelines/', 'WSAVA Global Nutrition Guidelines', 0.85, false, 'Manutenção geral.'),
  ('Glucosamine', 'Osteoarthritis', 'canine', 15, 30, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/17559970/', 'McCarthy G et al., 2007 — Glucosamine/chondroitin canine OA', 0.85, false, 'Sinergia com sulfato de condroitina.'),
  ('Chondroitin Sulfate', 'Osteoarthritis', 'canine', 15, 30, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/17559970/', 'McCarthy G et al., 2007', 0.85, false, 'Combinar com glucosamina.'),
  ('Undenatured Type II Collagen', 'Osteoarthritis', 'canine', 0.4, 1.0, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/17924023/', 'D''Altilio M et al., 2007 — UCII canine OA', 0.88, false, 'UC-II, dose baixa por mecanismo de tolerância oral.'),
  ('Resveratrol', 'Cellular Aging', 'canine', 5, 25, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/22588743/', 'Baur JA et al., 2006 — Resveratrol & lifespan', 0.7, false, 'Sirtuína-1 ativador, biodisponibilidade limitada — preferir trans-resveratrol.'),
  ('NMN', 'Cellular Aging', 'canine', 10, 50, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/30890773/', 'Yoshino J et al., 2018 — NMN longevity', 0.65, false, 'Precursor de NAD+. Estudos caninos limitados.'),
  ('Fisetin', 'Cellular Aging', 'canine', 1, 10, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/30279143/', 'Yousefzadeh MJ et al., 2018 — Fisetin senolytic', 0.6, false, 'Senolítico. Protocolo intermitente (2 dias/mês).'),
  ('CoQ10', 'Cardiac Disease', 'canine', 1, 5, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/17668857/', 'Plumb''s Veterinary Drug Handbook — Coenzyme Q10', 0.8, false, 'Forma ubiquinol preferida em geriátricos.'),
  ('SAMe', 'Hepatic Disease', 'canine', 18, 22, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/16363586/', 'Plumb''s Veterinary Drug Handbook — S-Adenosylmethionine', 0.92, false, 'Em jejum. Hepatoprotetor padrão.'),
  ('Silymarin', 'Hepatic Disease', 'canine', 50, 250, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/17565551/', 'Plumb''s — Silybin/Silymarin', 0.85, false, 'Forma silibina-fosfatidilcolina tem maior biodisponibilidade.'),
  ('Vitamin E', 'Antioxidant Support', 'canine', 10, 30, 'IU/kg', 1, 'oral', 'curated_study', 'https://nrc.nationalacademies.org/', 'NRC Nutrient Requirements of Dogs and Cats', 0.9, false, 'Tocoferol. Dose em IU/kg.'),
  ('Boswellia', 'Osteoarthritis', 'canine', 40, 80, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/15060828/', 'Reichling J et al., 2004 — Boswellia canine OA', 0.78, false, 'Inibidor de 5-LOX.'),
  ('Hyaluronic Acid', 'Osteoarthritis', 'canine', 0.3, 1.0, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/19473300/', 'Plumb''s — HA oral supplementation', 0.7, false, 'Oral; eficácia maior em formas de baixo PM.'),
  ('L-Carnitine', 'Cardiac Disease', 'canine', 50, 100, 'mg/kg', 2, 'oral', 'curated_study', 'https://onlinelibrary.wiley.com/doi/10.1111/j.1939-1676.1991.tb00942.x', 'Keene BW et al., 1991 — Carnitine deficiency DCM', 0.88, false, 'DCM, especialmente em raças predispostas (Boxer, Cocker).'),
  ('Taurine', 'Cardiac Disease', 'canine', 30, 100, 'mg/kg', 2, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/9498697/', 'Kittleson MD et al., 1997 — Taurine DCM', 0.9, false, 'Especialmente em DCM associada à dieta.'),
  ('Phosphatidylserine', 'Cognitive Dysfunction', 'canine', 1.5, 3.0, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/19261490/', 'Heath SE et al., 2007 — PS canine CDS', 0.78, false, 'Disfunção cognitiva canina (CDS).'),
  ('MCT Oil', 'Cognitive Dysfunction', 'canine', 100, 500, 'mg/kg', 1, 'oral', 'curated_study', 'https://pubmed.ncbi.nlm.nih.gov/20103029/', 'Pan Y et al., 2010 — MCT cognitive aging', 0.82, false, 'Triglicerídeos de cadeia média; ~5.5% da energia diária.')
ON CONFLICT DO NOTHING;
