// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqdfzzxiheyqfxrejmba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZGZ6enhpaGV5cWZ4cmVqbWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzgzNTIsImV4cCI6MjA1NzQxNDM1Mn0.v-i3c_aE3keuNOjUuSgq19IhO2tGbkG0Yu6oVTTa0UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);