// AUTO-GENERATED by scripts/generate-ai-inventory.mjs — do not edit by hand.
// Run: node scripts/generate-ai-inventory.mjs

export type AIInventoryStatus = 'obeys_screen' | 'hardcoded' | 'unregistered';
export type AIProvider = 'lovable_gateway' | 'google_direct' | 'openai_direct' | 'perplexity' | 'anthropic' | 'xai';

export interface AIInventoryRow {
  fn: string;
  providers: AIProvider[];
  status: AIInventoryStatus;
  tasks: string[];
  /** Model ids written literally in the function code (fallbacks included). */
  hardcoded_models: string[];
}

export const AI_INVENTORY: AIInventoryRow[] = [
  {
    "fn": "ai-task-healthcheck",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3-flash-preview"
    ]
  },
  {
    "fn": "ai-task-test",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-2.5-flash",
      "google/gemini-2.5-flash-lite",
      "google/gemini-2.5-pro",
      "google/gemini-3-flash-preview",
      "google/gemini-3-pro-preview",
      "openai/gpt-5",
      "openai/gpt-5-mini",
      "openai/gpt-5.4",
      "openai/gpt-5.4-mini",
      "openai/gpt-5.5"
    ]
  },
  {
    "fn": "analyze-all-cohorts-patterns",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3.5-flash"
    ]
  },
  {
    "fn": "analyze-cohort-patterns",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3.5-flash"
    ]
  },
  {
    "fn": "api-keys-manage",
    "providers": [
      "google_direct",
      "openai_direct",
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "sonar"
    ]
  },
  {
    "fn": "auto-tag-studies",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "study_tagging"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash-lite"
    ]
  },
  {
    "fn": "chat",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "clinical_chat_factual",
      "clinical_chat_critical"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "chat-meta-study",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3-flash-preview"
    ]
  },
  {
    "fn": "check-cohort-originality",
    "providers": [
      "lovable_gateway",
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-2.5-flash",
      "google/gemini-embedding-001",
      "sonar"
    ]
  },
  {
    "fn": "check-insight-originality",
    "providers": [
      "lovable_gateway",
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3.5-flash",
      "sonar"
    ]
  },
  {
    "fn": "document-chat",
    "providers": [
      "lovable_gateway",
      "google_direct"
    ],
    "status": "obeys_screen",
    "tasks": [
      "clinical_chat_factual"
    ],
    "hardcoded_models": [
      "google/...",
      "google/gemini-3-flash-preview",
      "google/gemini-3-pro-preview"
    ]
  },
  {
    "fn": "enrich-pet-food-product",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "food_enrichment"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-pro"
    ]
  },
  {
    "fn": "enrich-triplet",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "triplet_enrichment"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "evaluate-meta-study-reliability",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3-flash-preview"
    ]
  },
  {
    "fn": "external-sources-status",
    "providers": [
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "sonar"
    ]
  },
  {
    "fn": "extract-meta-study",
    "providers": [
      "lovable_gateway",
      "google_direct"
    ],
    "status": "obeys_screen",
    "tasks": [
      "meta_study_analysis"
    ],
    "hardcoded_models": [
      "google/gemini-3-pro-preview"
    ]
  },
  {
    "fn": "extract-pet-clinical-data",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "clinical_data_extraction"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "extract-study-entities",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "extraction_stage1",
      "extraction_stage2",
      "extraction_stage3"
    ],
    "hardcoded_models": [
      "google/gemini-3.5-flash"
    ]
  },
  {
    "fn": "gemini-file-search",
    "providers": [
      "google_direct"
    ],
    "status": "obeys_screen",
    "tasks": [
      "extraction_stage1"
    ],
    "hardcoded_models": [
      "gemini-3.1-pro-preview"
    ]
  },
  {
    "fn": "generate-audit",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3-flash-preview",
      "google/gemini-3.1-pro-preview",
      "openai/gpt-5-mini"
    ]
  },
  {
    "fn": "generate-meta-study-cover",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-2.5-flash-image"
    ]
  },
  {
    "fn": "generate-showcase",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3-flash-preview",
      "google/gemini-3.1-pro-preview",
      "openai/gpt-5-mini"
    ]
  },
  {
    "fn": "generate-synthetic-cohort",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3.5-flash"
    ]
  },
  {
    "fn": "generate-triplets",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "triplet_extraction"
    ],
    "hardcoded_models": [
      "google/gemini-3.5-flash"
    ]
  },
  {
    "fn": "hybrid-recommendation",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "geroprotector_stack",
      "lab_driven_adjustment",
      "treatment_proposal_12m"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "kg-evidence-gap-fill",
    "providers": [
      "lovable_gateway",
      "perplexity"
    ],
    "status": "obeys_screen",
    "tasks": [
      "kg_gap_fill"
    ],
    "hardcoded_models": [
      "google/gemini-3-flash-preview",
      "sonar-reasoning-pro"
    ]
  },
  {
    "fn": "parse-pet-exam-pdf",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "lab_pdf_parsing"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "perplexity-health",
    "providers": [
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "sonar",
      "sonar-deep-research",
      "sonar-pro",
      "sonar-reasoning",
      "sonar-reasoning-pro"
    ]
  },
  {
    "fn": "process-nutraceutical-spreadsheet",
    "providers": [
      "openai_direct"
    ],
    "status": "hardcoded",
    "tasks": [
      "spreadsheet_enrichment"
    ],
    "hardcoded_models": [
      "gpt-4o-mini"
    ]
  },
  {
    "fn": "project-pet-trajectory",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "trajectory_projection"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-pro"
    ]
  },
  {
    "fn": "provider-health",
    "providers": [
      "google_direct",
      "openai_direct",
      "perplexity",
      "anthropic",
      "xai"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "gemini-2.5-flash",
      "gpt-4o-mini",
      "sonar"
    ]
  },
  {
    "fn": "query-perplexity",
    "providers": [
      "perplexity"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "sonar"
    ]
  },
  {
    "fn": "relations-auditor",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "relations_auditor"
    ],
    "hardcoded_models": [
      "google/gemini-3.1-pro-preview"
    ]
  },
  {
    "fn": "suggest-cohort-ideas",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-3.1-pro-preview",
      "openai/gpt-5.4"
    ]
  },
  {
    "fn": "suggest-taxonomy-terms",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "taxonomy_suggestion"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "test-rag-similarity",
    "providers": [
      "google_direct"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": []
  },
  {
    "fn": "translate-and-categorize-conditions",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "translation_conditions"
    ],
    "hardcoded_models": [
      "google/gemini-3-pro-preview"
    ]
  },
  {
    "fn": "translate-conditions",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "translation_generic",
      "translation_conditions"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "translate-text",
    "providers": [
      "lovable_gateway"
    ],
    "status": "obeys_screen",
    "tasks": [
      "translation_generic"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-flash"
    ]
  },
  {
    "fn": "triplet-verification-runner",
    "providers": [
      "lovable_gateway"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": [
      "google/gemini-embedding-001",
      "openai/gpt-5.4-mini"
    ]
  },
  {
    "fn": "vectorize-study",
    "providers": [
      "google_direct"
    ],
    "status": "unregistered",
    "tasks": [],
    "hardcoded_models": []
  },
  {
    "fn": "web-dosage-lookup",
    "providers": [
      "lovable_gateway"
    ],
    "status": "hardcoded",
    "tasks": [
      "dosage_web_lookup"
    ],
    "hardcoded_models": [
      "google/gemini-2.5-pro"
    ]
  }
];
